#python
import os
import sys
import time
from time import sleep
os.system('clear')
def jalan(s):
  for c in s + '\n':
      sys.stdout.write(c)
      sys.stdout.flush()
      time.sleep(1./15)
jalan("\x1b[1;92mSlamat datang di Tools [ BOX-INGS ]...")
jalan("\x1b[1;92mInstall bahan terlebih dahulu...")

#main                                                                                                                 
sub = str(input("\033[1;93mApakah anda sudah follow instagram Admin? Y/T : "))
if sub == "Y":
   print ("\033[1;33mTerima Kasih :)")
   os.system('clear')
elif sub == "T":                                                                                                           
print ("\033[1;92mSilahkan follow terlebih dahulu...")
     os.system("xdg-open https://www.instagram.com/viwviaw/")
else:
  print ("\033[1;97mInput tidak ada\033[1;91m!!!")
  os.system("exit")
#banner
sleep(1)
print ("\033[31;1m██████╗  ██████╗ ██╗  ██╗     ██╗███╗   ██╗ ██████╗ ███████╗")
sleep(1)
print ("\033[31;1m██╔══██╗██╔═══██╗╚██╗██╔╝     ██║████╗  ██║██╔════╝ ██╔════╝")
sleep(1)
print ("\033[31;1m██████╔╝██║   ██║ ╚███╔╝█████╗██║██╔██╗ ██║██║  ███╗███████╗")
sleep(1)
print ("\033[37;1m██╔══██╗██║   ██║ ██╔██╗╚════╝██║██║╚██╗██║██║   ██║╚════██║")
sleep(1)
print ("\033[37;1m██████╔╝╚██████╔╝██╔╝ ██╗     ██║██║ ╚████║╚██████╔╝███████║")
sleep(1)
print ("\033[37;1m╚═════╝  ╚═════╝ ╚═╝  ╚═╝     ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚══════╝")
sleep(3)
print ("\033[33;1m      ●❯────────────────●●───────────────────❮●")
print ("\033[32;1m               𝙰𝚄𝚃𝙾𝚁  :\033[37;1m  𝙼𝚁.𝙸𝙽𝙶𝚂𝚂")
print ("\033[32;1m               𝚃𝙴𝙰𝙼   :\033[37;1m  𝙱𝙻𝙰𝙲𝙺𝙲𝚈𝙱𝙴𝚁𝚃𝙴𝙰𝙼")
print ("\033[32;1m               𝚃𝙾𝙾𝙻𝚂  :\033[37;1m  𝚂𝙰𝚈𝙳𝙾𝙶")
print ("\033[33;1m      ●❯────────────────●●───────────────────❮●")
print ("\033[36;1m                 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄")
print ("\033[36;1m                 ████▌▄▌▄▐▐▌█████")
print ("\033[36;1m                 ████▌▄▌▄▐▐▌▀████")
print ("\033[36;1m                 ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀")
print ("")
jalan("\033[33;1m       SUBSCRIBE CHANNEL YOU-TUBE [ \033[32;1mSAYDOG ]")
os.system("xdg-open https://www.youtube.com/channel/UCDoJC1ZJ_SmYKZZLD8PBmcQ")
sleep(2)
print ("\033[31;1m                    MENU-TOOLS")
print ("")
print ("\033[37;1m[\033[31;1m 1\033[37;1m ].\033[32;1m ɪɴsᴛᴀʟʟɪɴɢ ʙᴀʜᴀɴ")
print ("")
print ("\033[37;1m[\033[31;1m 2\033[37;1m ].\033[32;1m sᴀʏᴅᴏɢ-ғʀᴀᴍᴇᴡᴏʀᴋ")
print ("")
print ("\033[37;1m[\033[31;1m 3\033[37;1m ].\033[32;1m ᴍᴇᴛᴀsᴘʟᴏɪᴛ-ʜᴇʟᴘᴇʀ")
print ("")
print ("\033[37;1m[\033[31;1m 4\033[37;1m ].\033[32;1m ᴇᴠɪʟ ғᴀʀᴇᴍᴡᴏʀᴋ")
print ("")
print ("\033[37;1m[\033[31;1m 5\033[37;1m ].\033[32;1m ʟᴏɢɢᴇʀ-ᴄʀᴇᴀᴛᴏʀ")
print ("")
print ("\033[37;1m[\033[31;1m 6\033[37;1m ].\033[32;1m sᴀʏᴅᴏɢ")
print ("")
print ("\033[37;1m[\033[31;1m 7\033[37;1m ].\033[32;1m ᴛᴇʀᴍᴜx-ᴛʜᴇᴍᴇ")
print ("")
print ("\033[37;1m[\033[31;1m 8\033[37;1m ].\033[32;1m ᴠɪʀᴜs-ᴅʀᴏɪᴅ-ᴄʀᴇᴀᴛᴏʀ")
print ("")
print ("\033[37;1m[\033[31;1m 9\033[37;1m ].\033[32;1m ʀᴀɴsᴏᴍᴡᴀʀᴇ-ᴄʀᴇᴀᴛᴏʀ")
print ("")
print ("\033[37;1m[\033[31;1m 10\033[37;1m ].\033[32;1mᴛʀᴏᴊᴀɴ-ᴄʀᴇᴀᴛᴏʀ")
print ("")
print ("\033[37;1m[\033[31;1m 11\033[37;1m ].\033[32;1mᴇxɪᴛɪɴɢ ᴘʀᴏɢʀᴀᴍ")
print ("")
pil = str(input("\033[31;1mUSE TOOLS\033[37;1m  ➤➤ "))
if pil == "1":
   os.system('clear')
   jalan("\033[32;1mINSTALLING BAHAN...")
   sleep(1)
   os.system("pkg update && pkg upgrade")
   os.system("pkg install git")
   os.system("pkg install python")
   os.system("pkg install python2")
   os.system("pkg install wget")
   os.system("pkg install curl")
   os.system("pip2 install requests")
   os.system("pip2 install mechanize")
   os.system("pip2 install bs4")
   os.system("pip2 install colorama")
   os.system("pip install requests yagmail")
   os.system("pkg install nano")
   print ("\033[36;1m")
   jalan("\033[36;1mINSTALLING BAHAN SUCCESS...")
   sleep(2)
   os.system("python B.py")
elif  pil == "2":
     os.system('clear')
     jalan("\033[32;1mINSTALLING SAYDOG-FRAMEWORK...")
     sleep(1)
     os.system("git clone https://github.com/saydog/saydog-framework")
     sleep(1)
     jalan("\033[36;1mINSTALLING SUCCESS...")
     print ("")
elif pil == "3":
     os.system('clear')
     jalan("\033[32;1mINSTALLING METASPLOIT-HELPER...")
     sleep(1)
     os.system("git clone https://github.com/saydog/Metasploit-Helper")
     sleep(1)
     print ("")
     jalan("\033[36;1mINSTALLING SUCCESS...")
elif pil == "4":
     os.system('clear')
     jalan("\033[32;1mINSTALLING EVIL-FRAMEWORK...")
     sleep(1)
     os.system("git clone https://github.com/LOoLzeC/Evil-create-framework.git")
     sleep(1)
     print ("")
     jalan("\033[36;1mINSTALLING SUCCESS...")
elif pil == "5":
     os.system('clear')
     jalan("\003[32;1mINSTALLING LOGGER-CREATOR...")
     sleep(1)
     os.system("git clone https://github.com/saydog/Logger-creator")
     sleep(1)
     print ("")
     jalan("\033[36;1mINSTALLING SUCCESS...")
elif pil == "6":
     os.system('clear')
     jalan("\033[32;1mINSTALLING SAYDOG...")
     sleep(1)
     os.system("git clone https://github.com/saydog/SAYDOG")
     sleep(1)
     print ("")
     jalan("\033[36;1mINSTALLING SUCCESS...")
elif pil == "7":
     os.system('clear')
     jalan("\033[32;1mINSTALLING TERMUX-THEME...")                                                                         
     sleep(1)
     print ("")
     jalan("\033[36;1mINSTALLING SUCCESS...")
elif pil == "8":
     os.system('clear')                                                                                               
     jalan("\033[32;1mINSTALLING VIRUS-DROID-CREATOR...")
     sleep(1)
     os.system("git clone https://github.com/saydog/Virus-droid-creator")
     sleep(1)
     print ("")
     jalan("\033[36;1mINSTALLING SUCCESS...")
elif pil == "9":
     os.system('clear')
     jalan("\033[32;1mINSTALLING RANSOMWARE-CREATOR...")
     sleep(1)
     os.system("git clone https://github.com/saydog/Ransomware-creator")
     sleep(1)
     print ("")
     jalan("\033[36;1mINSTALLING SUCCESS...")
elif pil == "10":
     os.system('clear')
     jalan("\033[32;1mINSTALLING TROJAN-CREATOR...")
     sleep(1)
     os.system("git clone https://github.com/saydog/Trojan-creator")
     sleep(1)
     print ("")
     jalan("\033[36;1mINSTALLING SUCCESS...")
elif pil == "11":
     os.system('clear')
     jalan("\033[32;1mEXITING PROGRAM...")
     sleep(1)
     jalan("\033[33;1mTerima kasih sudah menggunakan Tools kami...")
     sleep(3)
     os.system('exit')